baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Big Bear BJJ'
enableRobotsTXT = true
disqusShortname = 'disqus_QUNH68KTBd'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
    homeText = 'Welcome to the bjj blog!' 
    dateFormat = "Jan 2, 2006"

[permalinks]
    blog = '/:filename/'

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3

[taxonomies]
  tag = "tags"